const New = [
    {
        id:1,
        name: 'Deal or no deal: How could Brexit play out?',
        descriptionLess: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and ',
        descriptionMore: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes',
        image:"/img/money/1.jpg",

    },
    {
    id:2,
    name: 'Brexit deal: What the UK and EU are yet to agree on',
    descriptionLess: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and ',
    descriptionMore: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes',
    image:"/img/money/2.jpg",
    },
    {
        id:3,
        name: 'May facing resignations of ministerial aides over fixed-odds',
        descriptionLess: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and ',
        descriptionMore: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes',
        image:"/img/money/3.jpg",
    },
    {
        id:4,
        name: 'Brexit deal: What the UK and EU are yet to agree on',
        descriptionLess: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and ',
        descriptionMore: 'Alan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes lan McGuinness, political reporter As the clock ticks towards exit day, Theresa May is battling to agree a Brexit deal with the European Union and steer it through parliament in time. British politics is in uncharted territory, so predicting with a high degree of certainty how the next few months will pan out is risky. Think of it like a chaotic game of chess. One move in either direction could throw the entire board into turmoil and completely alter what follows. There are a myriad of outcomes',
        image:"/img/money/4.jpg",
    },  
]

export default New